### ISSUE TITLE
Implement NLS model for image denoise problem

### ISSUE THREAD

**Issue by dpo** [JuliaSmoothOptimizers/RegularizedProblems.jl#45]
@MohamedLaghdafHABIBOULLAH

**Comment by MohamedLaghdafHABIBOULLAH** [comment]
@dpo The problem is that the denoising problem (PR) is, by nature, not an NLS model (because of the presence of the logarithm). That's why we can't use LM. Do you think I should look for another formulation of the denoising problem that admits an NLS model?

**Comment by dpo** [comment]
Couldn’t we minimize $\|y - b\|^2$?

**Comment by MohamedLaghdafHABIBOULLAH** [comment]
Ok, I see the issue. Basically, the code has been adopted from a Python version of the paper that I cited (to manipulate the wavelets and the FFT). However, the logarithmic formulation that uses L1 as a regularizer comes from this paper (https://arxiv.org/pdf/1604.08096.pdf) and Kanzow paper (https://arxiv.org/pdf/2210.07644.pdf) which I want to compare with because the previous paper I cited does not consider a non-smooth term and none of them did not use the 0 norm obviously (no convergence guarantee at the time)

**Comment by dpo** [comment]
Ok, please update your pull request.
